# Generated by Django 3.1 on 2020-08-14 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_max_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
