# Generated by Django 3.1 on 2020-08-18 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='auctions.user'),
            preserve_default=False,
        ),
    ]
